- /rest/1.3/analytics/status
- '/rest/1.3/analytics/{role}/subscription/details/compthirty'
- '/rest/1.3/analytics/{role}/subscription/details/compsixty'
- '/rest/1.3/analytics/{role}/subscription/details/cancelthirty'
- '/rest/1.3/analytics/{role}/subscription/details/cancelsixty'
- '/rest/1.3/analytics/{role}/subscription/details/startdate'
- '/rest/1.3/analytics/{role}/subscription/details/canceldate'
- '/rest/1.3/analytics/{role}/subscription/details/nextpmtdate'
- '/rest/1.3/analytics/{role}/subscription/details/status'
- '/rest/1.3/analytics/{role}/subscription/details'
- '/rest/1.3/analytics/{role}/subscription/trends'
- '/rest/1.3/analytics/{role}/{dimension}'
- '/rest/1.3/analytics/{role}/{dimension}/summary'
- /rest/1.3/debug
- /rest/1.3/images/list
- '/rest/1.3/orders/{receipt}/reinstate'
- '/rest/1.3/orders/{receipt}/pause'
- '/rest/1.3/orders/{receipt}/extend'
- '/rest/1.3/orders/{receipt}/changeProduct'
- '/rest/1.3/orders/{receipt}/changeAddress'
- /rest/1.3/orders/count
- /rest/1.3/orders/list
- '/rest/1.3/orders/{receipt}'
- '/rest/1.3/orders/{receipt}/upsells'
- '/rest/1.3/orders2/{receipt}/changeAddress'
- '/rest/1.3/orders2/{receipt}/changeDate'
- '/rest/1.3/orders2/{receipt}/changeProduct'
- '/rest/1.3/orders2/{receipt}/extend'
- '/rest/1.3/orders2/{receipt}'
- /rest/1.3/orders2/count
- /rest/1.3/orders2/list
- '/rest/1.3/orders2/{receipt}/upsells'
- '/rest/1.3/orders2/{receipt}/pause'
- '/rest/1.3/orders2/{receipt}/reinstate'
- '/rest/1.3/products/{sku}'
- /rest/1.3/products/list
- /rest/1.3/quickstats/count
- /rest/1.3/quickstats/accounts
- /rest/1.3/quickstats/list
- /rest/1.3/shipping/count
- /rest/1.3/shipping/list
- '/rest/1.3/shipping/shipnotice/{receipt}'
- /rest/1.3/shipping2/count
- /rest/1.3/shipping2/list
- '/rest/1.3/shipping2/shipnotice/{receipt}'
- /rest/1.3/shipping3/count
- /rest/1.3/shipping3/list
- '/rest/1.3/shipping3/shipnotice/{receipt}'
- '/rest/1.3/tickets/{receipt}'
- '/rest/1.3/tickets/{id}'
- /rest/1.3/tickets/count
- /rest/1.3/tickets/list
- '/rest/1.3/tickets/refundAmounts/{receipt}'
- '/rest/1.3/tickets/{id}/returned'
